apiVersion: v1
kind: ConfigMap
metadata:
  name: dbegd-postgres-config
  namespace: student-r-alo
  labels:
    app: dbegd
data:
  POSTGRES_DB: dbegd
  POSTGRES_USER: dbegd
  POSTGRES_HOST: dbegd-postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: dbegd-postgres-secret
  namespace: student-r-alo
  labels:
    app: dbegd
data:
  POSTGRES_PASSWORD: UzNjcjN0LkRibWFuMg==
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dbegd-postgres-claim
  namespace: student-r-alo
  labels:
    app: dbegd
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbegd-postgres
  namespace: student-r-alo
  labels:
    app: dbegd
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbegd
      tier: database
  template:
    metadata:
      labels:
        app: dbegd
        tier: database
    spec:
      containers:
        - name: postgres
          image: postgres:13.5
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              memory: 512Mi
              cpu: "0.5"
            requests:
              memory: 128Mi
              cpu: "0.1"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: dbegd-postgres-config
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: dbegd-postgres-config
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: dbegd-postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb             
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: dbegd-postgres-claim
---
apiVersion: v1
kind: Service
metadata:
 name: dbegd-postgres
 namespace: student-r-alo
 labels:
   app: dbegd
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: dbegd
    tier: database
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: angular-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
spec:
  rules:
    - host: student.cloud.htl-leonding.ac.at
      http:
        paths:
          - path: /r.alo/egd-user-with-quarkus/(.*)$
            pathType: Prefix
            backend:
              service:
                name: egd-user-with-quarkus
                port:
                  number: 80