---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 6ce25b19b87c0f401110b4457f95fd0ffa881790
    app.quarkus.io/build-timestamp: 2023-03-24 - 13:00:41 +0000
  labels:
    app.kubernetes.io/version: latest
    app.kubernetes.io/name: egd-user-with-quarkus
  name: egd-user-with-quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: latest
      app.kubernetes.io/name: egd-user-with-quarkus
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 6ce25b19b87c0f401110b4457f95fd0ffa881790
        app.quarkus.io/build-timestamp: 2023-03-24 - 13:00:41 +0000
      labels:
        app.kubernetes.io/version: latest
        app.kubernetes.io/name: egd-user-with-quarkus
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: egddocker/egd-user-with-quarkus:latest
          imagePullPolicy: Always
          name: egd-user-with-quarkus
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
      serviceAccountName: egd-user-with-quarkus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: egd-user-with-quarkus-view-secrets
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: view-secrets
subjects:
  - kind: ServiceAccount
    name: egd-user-with-quarkus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: egd-user-with-quarkus-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: egd-user-with-quarkus
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 6ce25b19b87c0f401110b4457f95fd0ffa881790
    app.quarkus.io/build-timestamp: 2023-03-24 - 13:00:41 +0000
  labels:
    app.kubernetes.io/name: egd-user-with-quarkus
    app.kubernetes.io/version: latest
  name: egd-user-with-quarkus
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: egd-user-with-quarkus
    app.kubernetes.io/version: latest
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/commit-id: 6ce25b19b87c0f401110b4457f95fd0ffa881790
    app.quarkus.io/build-timestamp: 2023-03-24 - 13:00:41 +0000
  labels:
    app.kubernetes.io/version: latest
    app.kubernetes.io/name: egd-user-with-quarkus
  name: egd-user-with-quarkus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-secrets
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
