name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: egddocker
          password: EGDPass$1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Test
        run: |
          cd Backend/egd-user-with-quarkus
          chmod +x mvnw
          ./mvnw install -DskipTests
          docker images
          docker push egddocker/egd-user-with-quarkus
          ls target/

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.25.4'
          
      - name: Install kubectl
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https
          curl -fsSLO https://github.com/int128/kubelogin/releases/download/v1.25.4/kubelogin_linux_amd64.zip
          unzip kubelogin_linux_amd64.zip kubelogin -d kubelogin
          mv kubelogin/kubelogin kubelogin/kubectl-oidc_login
          export PATH=$PATH:$(realpath kubelogin)
          mkdir ~/.kube
          echo "$KUBE_CONFIG" > ~/.kube/config
          echo "my Path"
          pwd
          echo "list"
          ls
          echo "list in Backend"
          ls Backend/
          kubectl apply -f Backend/egd-user-with-quarkus/target/kubernetes/kubernetes.yml
