      
name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Build with Maven
        run: mvn -f ./Backend/egd-user-with-quarkus/pom.xml clean package
      - name: Run Quarkus Tests
        run: mvn -f ./Backend/egd-user-with-quarkus -Dquarkus.http.test-port=8081 verify --no-transfer-progress
