name: Test Quarkus Application on Push

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: 'adopt@1.8'

    - name: Build with Maven
      run: mvn -B clean package --no-transfer-progress

    - name: Run Quarkus Tests
      run: mvn -B -Dquarkus.http.test-port=8081 verify --no-transfer-progress
